## TASK 1

1.
Write a function to compute 5/0 and use try/except to catch the exceptions.


In [0]:
def divide(a,b):
  try:
    result=a/b
    print("Output=", result)
  except ZeroDivisionError:
    print("Sorry ! can't divide with denominator as 0")

In [0]:
divide(5,0)

Sorry ! can't divide with denominator as 0


2.
Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

Hint: Subject,Verb and Object should be declared in the program as shown below.
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]


Output should come as below:
Americans play Baseball.

Americans play Cricket.

Americans watch Baseball.

Americans watch Cricket.

Indians play Baseball.

Indians play Cricket.

Indians watch Baseball.

Indians watch Cricket.

In [0]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [0]:
for i in subjects:
  for j in verbs:
    for k in objects:
      print(i,j,k)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## TASK 2

1.
Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.


In [2]:
import numpy as np
def vander_matrix(value, n, increasing=False):
    
    if not increasing:
        matx = np.array([x**(n-1-i) for x in value for i in range(n)]).reshape(value.size,n)
    elif increasing:
        matx = np.array([x**i for x in value for i in range(n)]).reshape(value.size,n)
    
    return matx

print("------------OUTPUT-------------\n")
value = np.array([1,2,3,4,5])
col = 3
matx_dec_order = vander_matrix(value,col,False)
matx_inc_order = vander_matrix(value,col,True)

print("The input array is:",value,"\n")
print("Number of columns in output matrix should be:",col,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",matx_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",matx_inc_order,"\n")

------------OUTPUT-------------

The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

